local J = require "jev.core.judge"

describe("judge", function()
  it("ships injection and abuse templates", function()
    assert.is_table(J.get("injection"))
    assert.is_table(J.get("abuse"))
    assert.is_string(J.get("injection").instructions)
  end)

  it("builds a prompt with only known templates", function()
    local p = J.build({ "injection", "nope" }, "hello", { path = "/x", method = "POST" })
    assert.equals("hello", p.text)
    assert.is_table(p.questions.injection)
    assert.is_nil(p.questions.nope)
    assert.equals("/x", p.context.path)
  end)

  it("errors with no known templates", function()
    local p, err = J.build({ "nope" }, "hello")
    assert.is_nil(p)
    assert.matches("no templates", err)
  end)

  it("reduces answers to the max probability", function()
    local s, name = J.reduce({ injection = 0.2, abuse = 0.7 })
    assert.equals(0.7, s)
    assert.equals("abuse", name)
  end)

  it("ignores garbage and clamps", function()
    local s = J.reduce({ a = "x", b = 0/0, c = 5 })
    assert.equals(1, s)
    assert.equals(0, (J.reduce({})))
  end)

  it("classifies a failed call by the provider's status", function()
    assert.equals(J.UNUSABLE, J.status_kind(200))
    assert.equals(J.UNUSABLE, J.status_kind(204))
    assert.equals(J.UNAVAILABLE, J.status_kind(500))
    assert.equals(J.UNAVAILABLE, J.status_kind(503))
    assert.equals(J.UNAVAILABLE, J.status_kind(429))
    for _, st in ipairs({ 400, 401, 403, 404, 408, 413, 422, 302 }) do
      assert.equals(J.REJECTED, J.status_kind(st), st)
    end
  end)

  it("counts only transport, timeout and unavailable against the provider", function()
    assert.is_true(J.counts("connection refused", J.TRANSPORT))
    assert.is_true(J.counts("timeout", J.TIMEOUT))
    assert.is_true(J.counts("laya http 503", J.UNAVAILABLE))
    assert.is_false(J.counts("laya http 400", J.REJECTED))
    assert.is_false(J.counts("openai-compat: no content", J.UNUSABLE))
    assert.is_false(J.counts(J.BUSY))
    -- a judge that gives no kind is counted, as before kinds
    assert.is_true(J.counts("some error"))
    assert.is_true(J.counts(nil))
  end)

  it("leads the reason with the kind the breaker did not count", function()
    assert.equals("rejected: laya http 400", J.reason("laya http 400", J.REJECTED))
    assert.equals("unusable: openai-compat: no content", J.reason("openai-compat: no content", J.UNUSABLE))
    assert.equals("laya http 503", J.reason("laya http 503", J.UNAVAILABLE))
    assert.equals("timeout", J.reason("timeout", J.TIMEOUT))
    assert.equals("error", J.reason(nil))
  end)
end)
