local J = require "jev.core.judge"

describe("judge", function()
  it("ships injection and abuse templates", function()
    assert.is_table(J.get("injection"))
    assert.is_table(J.get("abuse"))
    assert.is_string(J.get("injection").instructions)
  end)

  it("builds a prompt with only known templates", function()
    local p = J.build({ "injection", "nope" }, "hello", { path = "/x", method = "POST" })
    assert.equals("hello", p.text)
    assert.is_table(p.questions.injection)
    assert.is_nil(p.questions.nope)
    assert.equals("/x", p.context.path)
  end)

  it("errors with no known templates", function()
    local p, err = J.build({ "nope" }, "hello")
    assert.is_nil(p)
    assert.matches("no templates", err)
  end)

  it("reduces answers to the max probability", function()
    local s, name = J.reduce({ injection = 0.2, abuse = 0.7 })
    assert.equals(0.7, s)
    assert.equals("abuse", name)
  end)

  it("ignores garbage and clamps", function()
    local s = J.reduce({ a = "x", b = 0/0, c = 5 })
    assert.equals(1, s)
    assert.equals(0, (J.reduce({})))
  end)
end)
