FROM openresty/openresty:alpine-fat
RUN apk add --no-cache brotli-libs curl perl perl-app-cpanminus perl-dev make gcc musl-dev \
 && cpanm --notest --quiet Test::Nginx \
 && opm get ledgetech/lua-resty-http
WORKDIR /work/adapters/openresty
CMD ["prove", "-r", "t/"]
