-- bench/labels-from-log.lua
-- Turn operator feedback into the labels file `calibrate` reads.
--
-- The gateway never appends to a labels file: every /_jev/feedback call writes
-- one line into the jev access log (src="feedback") and nothing else. That log
-- is already collected, rotated and auditable, and the labels file is a
-- derived artifact you can regenerate at any time -- not state to back up.
--
-- Input:  one or more jev access logs (JSON per line). Later lines win, so an
--         operator who corrects themselves just POSTs again.
-- Output: `<fp>,<label>` lines, one per fingerprint, for
--         `lua bench/calibrate.lua <jev.log> <labels.csv>`.
--
-- Usage:
--   lua bench/labels-from-log.lua /var/log/nginx/access.log [more.log ...] \
--       [-o labels.csv] [--since <unix-ts>] [--by alice]
--
-- No dependencies beyond dkjson. Never reads request bodies; the log has none.

package.path = "./?.lua;./?/init.lua;" .. package.path
local json = require "dkjson"

local logs, out_path, since, only_by = {}, nil, nil, nil
do
  local i = 1
  while i <= #arg do
    local a = arg[i]
    if a == "-o" or a == "--out" then out_path = arg[i + 1]; i = i + 1
    elseif a == "--since" then since = assert(tonumber(arg[i + 1]), "--since needs a unix timestamp"); i = i + 1
    elseif a == "--by" then only_by = arg[i + 1]; i = i + 1
    elseif a == "-h" or a == "--help" then
      io.stderr:write("usage: lua bench/labels-from-log.lua <jev.log>... [-o labels.csv] [--since TS] [--by WHO]\n")
      os.exit(0)
    else logs[#logs + 1] = a end
    i = i + 1
  end
end
if #logs == 0 then
  io.stderr:write("usage: lua bench/labels-from-log.lua <jev.log>... [-o labels.csv] [--since TS] [--by WHO]\n")
  os.exit(2)
end

local ATTACK = { attack = true, bad = true, malicious = true, ["1"] = true, ["true"] = true }
local BENIGN = { benign = true, ok = true, good = true, ["0"] = true, ["false"] = true }

-- fp -> { label = "benign"|"attack", by = ..., ts = ..., rid = ..., n = <times reported> }
local labels, order = {}, {}
local lines, feedback_lines, refused = 0, 0, 0

for _, path in ipairs(logs) do
  local f = assert(io.open(path, "rb"), "cannot open " .. path)
  for raw in f:lines() do
    local line = raw:match("^%s*(.-)%s*$")
    if line ~= "" then
      lines = lines + 1
      local obj = json.decode(line)
      if type(obj) == "table" and obj.src == "feedback" and type(obj.fp) == "string" and obj.fp ~= "" then
        local lab = tostring(obj.label or ""):lower()
        local ts = tonumber(obj.ts) or 0
        local keep = (ATTACK[lab] or BENIGN[lab])
          and (not since or ts >= since)
          and (not only_by or obj.by == only_by)
        if keep then
          feedback_lines = feedback_lines + 1
          if obj.action == "refused" then refused = refused + 1 end
          local prev = labels[obj.fp]
          if not prev then order[#order + 1] = obj.fp end
          labels[obj.fp] = {
            label = ATTACK[lab] and "attack" or "benign",
            by = obj.by, ts = ts, rid = obj.rid, n = (prev and prev.n or 0) + 1,
          }
        end
      end
    end
  end
  f:close()
end

table.sort(order)

local fh = io.stdout
if out_path then fh = assert(io.open(out_path, "wb"), "cannot write " .. out_path) end

fh:write("# generated by bench/labels-from-log.lua from ", table.concat(logs, " "), "\n")
fh:write("# fingerprint,label   (last report per fingerprint wins)\n")
local n_benign, n_attack = 0, 0
for _, fp in ipairs(order) do
  local rec = labels[fp]
  if rec.label == "attack" then n_attack = n_attack + 1 else n_benign = n_benign + 1 end
  local note = rec.by and ("   # by " .. rec.by .. (rec.n > 1 and (", " .. rec.n .. " reports") or "")) or ""
  fh:write(fp, ",", rec.label, note, "\n")
end
if out_path then fh:close() end

io.stderr:write(string.format(
  "%d log lines, %d feedback lines -> %d fingerprints (%d benign, %d attack)%s\n",
  lines, feedback_lines, #order, n_benign, n_attack,
  refused > 0 and (", " .. refused .. " were refused at the gateway (renewal cap)") or ""))
if #order == 0 then
  io.stderr:write("nothing to label: is feedback.enabled on, and is the jev log format in use?\n")
  os.exit(1)
end
