worker_processes 1;
events {}
http {
    resolver 127.0.0.11 valid=5s;
    upstream app { server app:8081; }
    server {
        listen 80;
        location / { proxy_pass http://app; }
        include /etc/nginx/jev-auth-request.conf;
    }
}
