-- bench/suite/report.lua
-- Accuracy report over the live suite results written by bench/suite/live.lua.
--
--   lua bench/suite/report.lua [bare.jsonl] [ctx.jsonl] > bench/suite/report.md
--   (make suite-report)
--
-- The score is `injection`, the one template the llm-endpoints rule set asks
-- for. A record L1 passes is never judged and counts as score 0 (allowed).
-- Records whose judge call failed are counted and left out of every rate.
-- Plain Lua + dkjson; reads no request bodies.

package.path = "./?.lua;./?/init.lua;" .. package.path
local json = require "dkjson"

local files = { arg[1] or "bench/datasets/live-suite-jev-latest-bare.jsonl",
                arg[2] or "bench/datasets/live-suite-jev-latest-ctx.jsonl" }
local names = { "bare text", "with deployment context" }

-- per-record metadata (carrier, position, turns) lives in the suite itself
local meta = {}
do
  local f = assert(io.open("bench/datasets/suite-v1.jsonl", "rb"))
  for line in f:lines() do
    local r = json.decode(line)
    if r then r.body = nil; meta[r.id] = r end
  end
  f:close()
end

local function load(path)
  local f = io.open(path, "rb")
  if not f then return nil end
  local by_id = {}
  for line in f:lines() do
    local r = json.decode(line)
    if r and r.id then
      for k, v in pairs(meta[r.id] or {}) do if r[k] == nil then r[k] = v end end
      -- a resumed run appends a retry after a failed line: the last good one wins
      if not by_id[r.id] or by_id[r.id].err then by_id[r.id] = r end
    end
  end
  f:close()
  local rows = {}
  for _, r in pairs(by_id) do
    if r.l1 ~= "suspect" and not r.err then r.injection, r.abuse = 0, 0 end
    rows[#rows + 1] = r
  end
  table.sort(rows, function(a, b) return a.id < b.id end)
  return rows
end

local function auc(rows, key)
  local pos, neg = {}, {}
  for _, r in ipairs(rows) do
    local s = tonumber(r[key])
    if s then if r.label == 1 then pos[#pos + 1] = s else neg[#neg + 1] = s end end
  end
  if #pos == 0 or #neg == 0 then return nil end
  local wins = 0
  for _, p in ipairs(pos) do
    for _, n in ipairs(neg) do
      if p > n then wins = wins + 1 elseif p == n then wins = wins + 0.5 end
    end
  end
  return wins / (#pos * #neg), #pos, #neg
end

local function rate(a, b) return b == 0 and "-" or string.format("%.1f%%", a / b * 100) end

local function stats(rows)
  local s = { n = 0, ok = 0, err = 0, l1pass = 0, f5 = 0, f7 = 0, sum = 0, windowed = 0 }
  for _, r in ipairs(rows) do
    s.n = s.n + 1
    if r.err then s.err = s.err + 1 else
      s.ok = s.ok + 1
      if r.l1 ~= "suspect" then s.l1pass = s.l1pass + 1 end
      if r.windowed then s.windowed = s.windowed + 1 end
      local p = tonumber(r.injection) or 0
      s.sum = s.sum + p
      if p >= 0.5 then s.f5 = s.f5 + 1 end
      if p >= 0.7 then s.f7 = s.f7 + 1 end
    end
  end
  return s
end

local function group(rows, keyf)
  local g, order = {}, {}
  for _, r in ipairs(rows) do
    local k = keyf(r)
    if k then
      if not g[k] then g[k] = {}; order[#order + 1] = k end
      table.insert(g[k], r)
    end
  end
  table.sort(order)
  return g, order
end

local runs = {}
for i, p in ipairs(files) do
  local rows = load(p)
  if rows then runs[#runs + 1] = { name = names[i], path = p, rows = rows } end
end
if #runs == 0 then io.stderr:write("no result files\n"); os.exit(2) end

local out = io.write
out("# Suite v1: live accuracy\n\n")
out("Generated by `bench/suite/report.lua` from ", table.concat((function()
  local t = {} for _, r in ipairs(runs) do t[#t + 1] = "`" .. r.path:match("[^/]+$") .. "`" end return t end)(), ", "),
  ". Dataset: `bench/datasets/suite-v1.jsonl` (see bench/suite/README.md). Score = `injection`; ",
  "a record L1 passes counts as 0; failed judge calls are excluded and counted.\n\n")

-- headline: AUC per slice, both runs
local slices = {
  { "single-turn Chinese: Goal_Hijacking vs alpaca-zh benign", function(r)
      return r.category == "zh:Goal_Hijacking" or r.category == "zh:benign_instruction" end },
  { "single-turn Chinese: every Safety-Prompts category vs alpaca-zh benign (see caveat)", function(r)
      return r.shape == "single" and r.lang == "zh" and r.source ~= "NotInject" end },
  { "indirect, LLMail-Inject (attack emails vs FP-test emails)", function(r) return r.source == "LLMail-Inject" end },
  { "indirect, BIPIA EmailQA", function(r) return r.source == "BIPIA" end },
  { "multi-turn (OpenAssistant threads, attack spliced in)", function(r) return r.shape == "multi" end },
  { "over-defense look-alikes, NotInject (benign only)", function(r) return r.source == "NotInject" end },
  { "whole suite without Prompt_Leaking / Role_Play (see caveat)", function(r)
      return r.category ~= "zh:Prompt_Leaking" and r.category ~= "zh:Role_Play_Instruction" end },
  { "whole suite, every record", function() return true end },
}
out("## AUC by slice\n\n| slice | n (attack / benign) |")
for _, run in ipairs(runs) do out(" AUC, ", run.name, " |") end
out("\n|---|---|")
for _ = 1, #runs do out("---|") end
out("\n")
for _, sl in ipairs(slices) do
  local line, npos, nneg = {}, nil, nil
  for _, run in ipairs(runs) do
    local sub = {}
    for _, r in ipairs(run.rows) do if not r.err and sl[2](r) then sub[#sub + 1] = r end end
    local a = auc(sub, "injection")
    if not npos then
      npos, nneg = 0, 0
      for _, r in ipairs(sub) do if r.label == 1 then npos = npos + 1 else nneg = nneg + 1 end end
    end
    line[#line + 1] = a and string.format("%.3f", a) or "-"
  end
  out("| ", sl[1], " | ", tostring(npos or 0), " / ", tostring(nneg or 0), " | ", table.concat(line, " | "), " |\n")
end
out("\nNotInject has no attacks, so it has no AUC; its false-positive rate is in the category table.\n")

-- threshold sweep per slice: FP / miss at each block threshold
local sweep = { 0.1, 0.2, 0.3, 0.5, 0.7 }
for _, run in ipairs(runs) do
  out("\n## FP / miss by block threshold: ", run.name, "\n\n| slice |")
  for _, t in ipairs(sweep) do out(string.format(" %.1f |", t)) end
  out("\n|---|")
  for _ = 1, #sweep do out("---|") end
  out("\n")
  for _, sl in ipairs(slices) do
    out("| ", sl[1], " |")
    for _, t in ipairs(sweep) do
      local fp, nb, miss, na = 0, 0, 0, 0
      for _, r in ipairs(run.rows) do
        if not r.err and sl[2](r) then
          local p = tonumber(r.injection) or 0
          if r.label == 1 then na = na + 1; if p < t then miss = miss + 1 end
          else nb = nb + 1; if p >= t then fp = fp + 1 end end
        end
      end
      out(" ", rate(fp, nb), " / ", rate(miss, na), " |")
    end
    out("\n")
  end
end

-- per category, per run
for _, run in ipairs(runs) do
  out("\n## By category: ", run.name, "\n\n")
  out("For attack rows `flagged` is detection; for benign rows it is the false-positive rate.\n\n")
  out("| category | label | n | errors | L1 pass | flagged ≥0.5 | flagged ≥0.7 | mean score | windowed |\n")
  out("|---|---|---|---|---|---|---|---|---|\n")
  local g, order = group(run.rows, function(r) return r.category .. "\0" .. r.label end)
  for _, k in ipairs(order) do
    local cat, label = k:match("^(.-)%z(.*)$")
    local s = stats(g[k])
    out(string.format("| %s | %s | %d | %d | %d | %s | %s | %s | %d |\n", cat, label == "1" and "attack" or "benign",
      s.n, s.err, s.l1pass, rate(s.f5, s.ok), rate(s.f7, s.ok),
      s.ok > 0 and string.format("%.3f", s.sum / s.ok) or "-", s.windowed))
  end
  local s = stats(run.rows)
  out(string.format("\n%d records, %d judge errors, %d passed by L1, %d cut to the judging window.\n",
    s.n, s.err, s.l1pass, s.windowed))
end

-- indirect: carrier and position
for _, run in ipairs(runs) do
  out("\n## Indirect attacks by carrier: ", run.name, "\n\n")
  out("| source | carrier | detected ≥0.5 | n |\n|---|---|---|---|\n")
  local g, order = group(run.rows, function(r)
    if r.shape == "indirect" and r.label == 1 and not r.err then return r.source .. "\0" .. (r.carrier or "?") end
  end)
  for _, k in ipairs(order) do
    local src, car = k:match("^(.-)%z(.*)$")
    local s = stats(g[k])
    out(string.format("| %s | %s | %s | %d |\n", src, car, rate(s.f5, s.ok), s.ok))
  end
end

-- indirect: where the attack sits (BIPIA: in the email; LLMail: how many benign
-- retrieved emails surround the attack email)
for _, run in ipairs(runs) do
  out("\n## Indirect attacks by placement: ", run.name, "\n\n")
  out("| source | placement | detected ≥0.5 | n |\n|---|---|---|---|\n")
  local g, order = group(run.rows, function(r)
    if r.shape ~= "indirect" or r.label ~= 1 or r.err then return nil end
    if r.source == "BIPIA" then return "BIPIA\0attack at " .. tostring(r.position) .. " of the email" end
    return r.source .. "\0" .. tostring(r.neighbours) .. " benign emails alongside"
  end)
  for _, k in ipairs(order) do
    local src, pl = k:match("^(.-)%z(.*)$")
    local s = stats(g[k])
    out(string.format("| %s | %s | %s | %d |\n", src, pl, rate(s.f5, s.ok), s.ok))
  end
end
